# File: L10/verifyPSL264.g
# Author: William DeMeo
# Date: 2026.09.17
#
# Description: recomputes, independently of the paper, the interval that
# Chenxiao Tian's note "The exceptional seven-element lattice as a subgroup
# interval in PSL2(64)" (dated 2026.08.28) claims is isomorphic to L10 (the
# paper's numbering; L7 in DeMeo's thesis and in Tian's note): G = SL(2,64),
# which is PSL(2,64) since the characteristic is two, and H = SL(2,2), the
# subgroup generated by the two matrices
#
#     u = [[1,1],[0,1]]   and   v = [[0,1],[1,0]]
#
# over GF(64), which is isomorphic to S3.  Nothing here is taken from the
# note's tables: GAP's IntermediateSubgroups computes the subgroups strictly
# between H and G together with their cover relation, and the interval is then
# tested against L10 by brute force.
#
# The program also corroborates each step of the note's proof separately:
# the normalizer of H and the centralizer and normalizer of its Sylow
# 3-subgroup (Lemma 2.1), the maximal subgroups of G and the number of
# conjugacy classes of S3, A5 and PSL(2,8) (Proposition 2.2), the two incidence
# counts 4368 * 10 and 520 * 84 that give the unique A5 and the unique PSL(2,8)
# above H (Lemma 2.3), the identification of the three maximal overgroups as the
# subfield groups SL(2,4) and SL(2,8) and the torus normalizer (Lemma 2.4),
# the generation of G by u, v and a diagonal generator (Lemma 3.2), and the
# table of marks of L2(64) in TomLib (Section 4).
#
# Run from the repository root, with a GAP that has the tomlib package:
#
#     gap -A -q -b L10/verifyPSL264.g
#
# Result (GAP 4.15.1, TomLib 1.2.11, 2026.09.17): see L10/results/verifyPSL264.txt,
# which the run below reproduces line for line.  The interval has exactly five
# proper intermediate subgroups, of orders 18, 42, 60, 126 and 504 and types
# D18, D42, A5, D126, PSL(2,8), with covers
#
#     [[0,1],[0,2],[0,3],[1,4],[1,5],[2,4],[3,6],[4,6],[5,6]]
#
# and it is isomorphic to L10.

SetPrintFormattingStatus("*stdout*", false);
Read("L10/latticeTests.g");

F := GF(64);
z := Zero(F);
o := One(F);
u := ImmutableMatrix(F, [[o,o],[z,o]]);
v := ImmutableMatrix(F, [[z,o],[o,z]]);
G := SL(2,64);
H := Subgroup(G, [u,v]);
Print("|G| = ", Size(G), "\n");
Print("|H| = ", Size(H), "  H <= G: ", IsSubgroup(G,H), "  H = ", StructureDescription(H), "\n");

# Lemma 2.1: N_G(H) = H, C_G(C) = C63, N_G(C) = D126, one class of S3.
C := SylowSubgroup(H, 3);
Print("|N_G(H)| = ", Size(Normalizer(G, H)), "\n");
Print("|C_G(C)| = ", Size(Centralizer(G, C)), "  N_G(C) = ", StructureDescription(Normalizer(G, C)),
      " of order ", Size(Normalizer(G, C)), "\n");
Print("conjugacy classes of S3 in G: ", Length(IsomorphicSubgroups(G, SymmetricGroup(3))), "\n");
Print("conjugates of H: ", Index(G, Normalizer(G, H)), "\n");

# The interval itself.
t := Runtime();
r := IntermediateSubgroups(G, H);
Print("IntermediateSubgroups: ", Runtime() - t, " ms\n");
n := Length(r.subgroups);
Print("proper intermediate subgroups: ", n, "\n");
Print("orders: ", List(r.subgroups, Size), "\n");
Print("structures: ", List(r.subgroups, StructureDescription), "\n");
Print("covers (0 = H, ", n + 1, " = G): ", r.inclusions, "\n");
leq := FLR_LeqFromCovers(n + 2, r.inclusions);
Print("up-sets (1 = H, ", n + 2, " = G): ", leq, "\n");
Print("[H, G] isomorphic to L10: ", FLR_IsTarget(leq), "\n");

# Proposition 2.2: the maximal subgroups of G, one class of each type.
t := Runtime();
mx := MaximalSubgroupClassReps(G);
Print("maximal subgroup class orders: ", SortedList(List(mx, Size)), "  (", Runtime() - t, " ms)\n");
Print("maximal subgroup structures: ", List(mx, StructureDescription), "\n");
Print("conjugacy classes of A5 in G: ", Length(IsomorphicSubgroups(G, AlternatingGroup(5))), "\n");
Print("conjugacy classes of PSL(2,8) in G: ", Length(IsomorphicSubgroups(G, PSL(2,8))), "\n");

# Lemma 2.3: the incidence counts, and Lemma 2.4: the three maximal overgroups.
A := First(r.subgroups, X -> Size(X) = 60);
D := First(r.subgroups, X -> Size(X) = 126);
L := First(r.subgroups, X -> Size(X) = 504);
Print("conjugates of A5: ", Index(G, Normalizer(G, A)), "  S3 subgroups of one A5: ", Index(A, Normalizer(A, H)),
      "  product: ", Index(G, Normalizer(G, A)) * Index(A, Normalizer(A, H)), "\n");
Print("conjugates of PSL(2,8): ", Index(G, Normalizer(G, L)), "  S3 subgroups of one PSL(2,8): ",
      Sum(List(IsomorphicSubgroups(L, SymmetricGroup(3)), e -> Index(L, Normalizer(L, Image(e))))),
      "  product: ", Index(G, Normalizer(G, L)) *
      Sum(List(IsomorphicSubgroups(L, SymmetricGroup(3)), e -> Index(L, Normalizer(L, Image(e))))), "\n");
Print("conjugates of D126: ", Index(G, Normalizer(G, D)), "\n");
Print("the A5 above H has all entries in GF(4): ", ForAll(GeneratorsOfGroup(A), m -> ForAll(Flat(m), x -> x in GF(4))), "\n");
Print("the PSL(2,8) above H has all entries in GF(8): ", ForAll(GeneratorsOfGroup(L), m -> ForAll(Flat(m), x -> x in GF(8))), "\n");
Print("the D126 above H is N_G(C): ", D = Normalizer(G, C), "\n");

# Lemma 3.2: G = < u, v, h > with h = diag(alpha, alpha^-1).
alpha := PrimitiveRoot(F);
h := ImmutableMatrix(F, [[alpha, z], [z, alpha^-1]]);
Print("<u, v, h> = G: ", Size(Group(u, v, h)) = Size(G), "\n");

# Section 4: the table of marks of L2(64).
if LoadPackage("tomlib") = true then
  tom := TableOfMarks("L2(64)");
  ords := OrdersTom(tom);
  nc := Length(ords);
  Print("TomLib L2(64): ", nc, " classes of subgroups, |G| = ", ords[nc], "\n");
  over := [];
  for i in Filtered([1 .. nc], i -> ords[i] = 6) do
    over := Filtered([1 .. nc], j -> ContainingTom(tom, i, j) > 0);
    Print("class ", i, " of order 6: overgroup classes ", over, ", orders ", List(over, j -> ords[j]),
          ", multiplicities ", List(over, j -> ContainingTom(tom, i, j)), "\n");
  od;
else
  Print("tomlib is not available; the table-of-marks check was skipped\n");
fi;
QUIT_GAP(0);
